#!/bin/sh

set -ex

PACKAGE=jxrlib

VERSION=${VERSION:-$2}
TARFILE=${TARFILE:-$3}

if [ -z ${VERSION}]; then
VERSION=`dpkg-parsechangelog | sed -n -e 's/^Version: \(.*\)-[^-]*$/\1/p'`
fi
if [ -z ${TARFILE}]; then
TARFILE=${PACKAGE}_${VERSION}.orig.tar.gz
fi

FOLDER=${PACKAGE}-${VERSION}

# 1.0
# wget -O jxrlib.tgz "http://download-codeplex.sec.s-msft.com/Download/SourceControlFileDownload.ashx?ProjectName=jxrlib&changeSetId=e96b2a813d13aa50353fb0f17cb5e6762ef2e37d"
# 1.1
wget -O jxrlib.tgz "http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=jxrlib&DownloadId=685250&FileTime=130142428056630000&Build=20552"

tar xfz jxrlib.tgz

rm jxrlib/bin/*.exe
mv jxrlib ${FOLDER}

GZIP="--best --no-name" tar czf ${TARFILE} ${FOLDER}
rm -rf ${FOLDER}
rm jxrlib.tgz
